name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */4 * * *"  # ogni 4 ore
  workflow_dispatch:      # avvio manuale opzionale

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -L --silent --show-error "https://forgialean.streamlit.app/" || true
